ALTER TABLE USUARIO
    ADD CONSTRAINT UQ_USUARIO_CORREO UNIQUE (CORREO);

ALTER TABLE GRUPO
    ADD CONSTRAINT UQ_GRUPO_NUMERO UNIQUE (NUMERO);

ALTER TABLE DEPARTAMENTO
    ADD CONSTRAINT UQ_DEPARTAMENTO_NOMBRE UNIQUE (NOMBRE);

ALTER TABLE AREA
    ADD CONSTRAINT UQ_AREA_NOMBRE UNIQUE (NOMBRE);

ALTER TABLE MATERIA
    ADD CONSTRAINT UQ_MATERIA_NOMBRE UNIQUE (NOMBRE);

ALTER TABLE CENTRODEESTUDIOS
    ADD CONSTRAINT UQ_CENTRODEESTUDIOS_NOMBRE UNIQUE (NOMBRE);

ALTER TABLE NUCLEODEFORMACION
    ADD CONSTRAINT UQ_NUCLEODEFORMACION_NOMBRE UNIQUE (NOMBRE);

ALTER TABLE PROGRAMAACADEMICO
    ADD CONSTRAINT UQ_PROGRAMAACADEMICO_NOMBRE UNIQUE (NOMBRE);