ALTER TABLE ESTUDIANTES
    ADD CONSTRAINT UQ_ESTUDIANTES_correo UNIQUE (correo);

ALTER TABLE ESTUDIANTES
    ADD CONSTRAINT UQ_ESTUDIANTES_telefono UNIQUE (telefono);

ALTER TABLE PROFESORES
    ADD CONSTRAINT UQ_PROFESORES_correo UNIQUE (correo);

ALTER TABLE PROFESORES
    ADD CONSTRAINT UQ_PROFESORES_telefono UNIQUE (telefono);

ALTER TABLE DIRECTORES
    ADD CONSTRAINT UQ_DIRECTORES_correo UNIQUE (correo);

ALTER TABLE DIRECTORES
    ADD CONSTRAINT UQ_DIRECTORES_telefono UNIQUE (telefono);

ALTER TABLE ESTUDIANTES
    ADD CONSTRAINT UQ_ESTUDIANTES_documentoIdentidad UNIQUE (documentoIdentidad);

ALTER TABLE DEPARTAMENTOS
    ADD CONSTRAINT UQ_DEPARTAMENTOS_nombre UNIQUE (nombre);

ALTER TABLE GRUPOS
    ADD CONSTRAINT UQ_GRUPO_numero UNIQUE (numero);

ALTER TABLE AREAS
    ADD CONSTRAINT UQ_AREAS_nombre UNIQUE (nombre);

ALTER TABLE MATERIAS
    ADD CONSTRAINT UQ_MATERIAS_nombre UNIQUE (nombre);

ALTER TABLE CENTROSDEESTUDIOS
    ADD CONSTRAINT UQ_CENTRODEESTUDIOS_NOMBRE UNIQUE (NOMBRE);

ALTER TABLE NUCLEOSDEFORMACION
    ADD CONSTRAINT UQ_NUCLEODEFORMACION_NOMBRE UNIQUE (NOMBRE);

ALTER TABLE PROGRAMASACADEMICOS
    ADD CONSTRAINT UQ_PROGRAMAACADEMICO_nombre UNIQUE (nombre);