--Eliminar triggers
DROP TRIGGER trg_fecha_registro_estudiante;
DROP TRIGGER trg_validar_nota;
DROP TRIGGER trg_cancelacion_estudiante;
DROP TRIGGER trg_presupuesto_director;
DROP TRIGGER trg_validar_telefono_profesor;
DROP TRIGGER trg_validar_telefono_director;
DROP TRIGGER trg_validar_telefono_estudiante;
DROP TRIGGER trg_actualizar_notificacion;