--Paquete ESTUDIANTE
CREATE OR REPLACE PACKAGE PKG_ESTUDIANTE
IS
    PROCEDURE consultarHistorialAcademico(C_HISTORIAL OUT SYS_REFCURSOR);
    PROCEDURE consultarInscripciones(C_INSCRIPCIONES OUT SYS_REFCURSOR);
    PROCEDURE consultarHorario(C_HORARIO OUT SYS_REFCURSOR);
    PROCEDURE inscribirMateria(idEstudiante VARCHAR, idMateria VARCHAR, idGrupo VARCHAR);
END;
/

--Paquete PROFESOR
CREATE OR REPLACE PACKAGE PKG_PROFESOR
IS
    PROCEDURE consultarEstudiantesMateria(C_ESTUDIANTES OUT SYS_REFCURSOR, idMateria VARCHAR, idGrupo VARCHAR);
    PROCEDURE consultarNotasMateria(C_NOTAS OUT SYS_REFCURSOR, idMateria VARCHAR, idGrupo VARCHAR);
    PROCEDURE registrarNota(idEstudiante VARCHAR, idMateria VARCHAR, valorNota NUMBER, tipoEvaluacion VARCHAR);
    PROCEDURE consultarHorarioProfesor(C_HORARIO OUT SYS_REFCURSOR, idProfesor VARCHAR);
END;
/

--Paquete DIRECTOR
CREATE OR REPLACE PACKAGE PKG_DIRECTOR
IS
    PROCEDURE consultarEstadisticasAprobacion(C_ESTADISTICAS OUT SYS_REFCURSOR, idDepartamento VARCHAR);
    PROCEDURE consultarCargaDocente(C_CARGA OUT SYS_REFCURSOR, idDepartamento VARCHAR);
    PROCEDURE consultarInformeRendimiento(C_RENDIMIENTO OUT SYS_REFCURSOR, semestre VARCHAR);
    PROCEDURE asignarCargaDocente(idProfesor VARCHAR, idMateria VARCHAR, idGrupo VARCHAR);
END;
/

--Paquete EMPRESA
CREATE OR REPLACE PACKAGE PKG_EMPRESA
IS
    PROCEDURE consultarPracticantes(C_PRACTICANTES OUT SYS_REFCURSOR, idEmpresa VARCHAR);
    PROCEDURE registrarOfertaPractica(idEmpresa VARCHAR, descripcion VARCHAR, requisitos VARCHAR, salario NUMBER);
    PROCEDURE consultarConvenios(C_CONVENIOS OUT SYS_REFCURSOR, idEmpresa VARCHAR);
END;
/

--Paquete ENTIDAD_GUBERNAMENTAL
CREATE OR REPLACE PACKAGE PKG_ENTIDAD_GUBERNAMENTAL
IS
    PROCEDURE consultarEstadisticasEgresados(C_ESTADISTICAS OUT SYS_REFCURSOR);
    PROCEDURE consultarProgramasAcademicos(C_PROGRAMAS OUT SYS_REFCURSOR);
    PROCEDURE consultarReporteInstitucional(C_REPORTE OUT SYS_REFCURSOR, anio VARCHAR);
END;
/
