ALTER TABLE ADDRESS
ADD CONSTRAINT PK_Address PRIMARY KEY (ADDRESSID);

ALTER TABLE CUSTOMER
ADD CONSTRAINT PK_Customer PRIMARY KEY (CUSTOMERID);

ALTER TABLE CUSTOMERADDRESS
ADD CONSTRAINT PK_CustomerAddress PRIMARY KEY (CUSTOMERID, ADDRESSTYPE);

ALTER TABLE SALESORDERHEADER
ADD CONSTRAINT PK_SalesOrderHeader PRIMARY KEY (SALESORDERID);

ALTER TABLE SALESORDERDETAIL
ADD CONSTRAINT PK_SalesOrderDetail PRIMARY KEY (SALESORDERDETAILID);

ALTER TABLE PRODUCT
ADD CONSTRAINT PK_Product PRIMARY KEY (PRODUCTID);

ALTER TABLE PRODUCTMODEL
ADD CONSTRAINT PK_ProductModel PRIMARY KEY (PRODUCTMODELID);

ALTER TABLE PRODUCTCATEGORY
ADD CONSTRAINT PK_ProductCategory PRIMARY KEY (PRODUCTCATEGORYID);

ALTER TABLE PRODUCTMODELPRODUCTDESCRIPTION
ADD CONSTRAINT PK_ProductModelProductDescription PRIMARY KEY (PRODUCTMODELID, PRODUCTDESCRIPTIONID, CULTURE);

ALTER TABLE PRODUCTDESCRIPTION
ADD CONSTRAINT PK_ProductDescription PRIMARY KEY (PRODUCTDESCRIPTIONID);

ALTER TABLE CUSTOMERADDRESS
ADD CONSTRAINT FK_CustomerAddress_Customer FOREIGN KEY (CUSTOMERID) REFERENCES Customer(CUSTOMERID);

ALTER TABLE CUSTOMERADDRESS
ADD CONSTRAINT FK_CustomerAddress_Address FOREIGN KEY (ADDRESSID) REFERENCES Address(ADDRESSID);

ALTER TABLE SALESORDERHEADER
ADD CONSTRAINT FK_SalesOrderHeader_Customer FOREIGN KEY (CUSTOMERID) REFERENCES Customer(CUSTOMERID);

ALTER TABLE SALESORDERHEADER
ADD CONSTRAINT FK_SalesOrderHeader_BillTo FOREIGN KEY (BILLTOADDRESSID) REFERENCES Address(ADDRESSID);

ALTER TABLE SALESORDERHEADER
ADD CONSTRAINT FK_SalesOrderHeader_ShipTo FOREIGN KEY (SHIPTOADDRESSID) REFERENCES Address(ADDRESSID);

ALTER TABLE SALESORDERDETAIL
ADD CONSTRAINT FK_SalesOrderDetail_Order FOREIGN KEY (SALESORDERID) REFERENCES SalesOrderHeader(SALESORDERID);

ALTER TABLE SALESORDERDETAIL
ADD CONSTRAINT FK_SalesOrderDetail_Product FOREIGN KEY (PRODUCTID) REFERENCES Product(PRODUCTID);

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_Product_Model FOREIGN KEY (PRODUCTMODELID) REFERENCES ProductModel(PRODUCTMODELID);

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_Product_Category FOREIGN KEY (PRODUCTCATEGORYID) REFERENCES ProductCategory(PRODUCTCATEGORYID);

ALTER TABLE PRODUCTCATEGORY
ADD CONSTRAINT FK_ProductCategory_Parent FOREIGN KEY (PARENTPRODUCTCATEGORYID) REFERENCES ProductCategory(PRODUCTCATEGORYID);

ALTER TABLE PRODUCTMODELPRODUCTDESCRIPTION
ADD CONSTRAINT FK_ProductModelProductDescription_Model FOREIGN KEY (PRODUCTMODELID) REFERENCES ProductModel(PRODUCTMODELID);

ALTER TABLE PRODUCTMODELPRODUCTDESCRIPTION
ADD CONSTRAINT FK_ProductModelProductDescription_Description FOREIGN KEY (PRODUCTDESCRIPTIONID) REFERENCES ProductDescription(PRODUCTDESCRIPTIONID);

ALTER TABLE CUSTOMER
ADD CONSTRAINT UK_Customer UNIQUE (EMAILADDRESS);