ALTER TABLE DESAYUNO
ADD CONSTRAINT PK_Desayuno PRIMARY KEY (NOMBRE);

ALTER TABLE BASICO
ADD CONSTRAINT PK_Basico PRIMARY KEY (NOMBRE);

ALTER TABLE FACTURA
ADD CONSTRAINT PK_Factura PRIMARY KEY (NUMERO);

ALTER TABLE CLIENTE
ADD CONSTRAINT PK_Client PRIMARY KEY (CEDULA);

ALTER TABLE TELEFONOS
ADD CONSTRAINT PK_Telefonos PRIMARY KEY (CEDULA_CLIENTE);

ALTER TABLE ESTILO
ADD CONSTRAINT PK_Estilo PRIMARY KEY (NOMBRE);

ALTER TABLE CAMPAÑA
ADD CONSTRAINT PK_Campaña PRIMARY KEY (ID);

ALTER TABLE FISICO
ADD CONSTRAINT PK_Fisico PRIMARY KEY (ID);

ALTER TABLE DIGITAL
ADD CONSTRAINT PK_Digital PRIMARY KEY (ID);

ALTER TABLE ESPECIFICACION
ADD CONSTRAINT PK_Especificacion PRIMARY KEY (URL);

ALTER TABLE SEPIDEN
ADD CONSTRAINT PK_Sepiden PRIMARY KEY (NOMBRE_PRODUCTO, NUMERO_FACTURA);

ALTER TABLE SEVENDENEN
ADD CONSTRAINT PK_Sevendenen PRIMARY KEY (NOMBRE_ESTILO, NOMBRE_PRODUCTO);

