TRUNCATE TABLE DESAYUNO;
DROP TABLE DESAYUNO;

TRUNCATE TABLE BASICO;
DROP TABLE BASICO;

TRUNCATE TABLE FACTURA;
DROP TABLE FACTURA;

TRUNCATE TABLE CLIENTE;
DROP TABLE CLIENTE;

TRUNCATE TABLE TELEFONOS;
DROP TABLE TELEFONOS;

TRUNCATE TABLE ESTILO;
DROP TABLE ESTILO;

TRUNCATE TABLE CAMPAÑA;
DROP TABLE CAMPAÑA;

TRUNCATE TABLE FISICO;
DROP TABLE FISICO;

TRUNCATE TABLE DIGITAL;
DROP TABLE DIGITAL;

TRUNCATE TABLE ESPECIFICACION;
DROP TABLE ESPECIFICACION;

TRUNCATE TABLE SEPIDEN;
DROP TABLE SEPIDEN;

TRUNCATE TABLE SEVENDENEN;
DROP TABLE SEVENDENEN;

