ALTER TABLE ESTUDIANTE
ADD CONSTRAINT FK_ESTUDIANTE_CANCELACION FOREIGN KEY (IDCANCELACION)
REFERENCES CANCELACION (IDCANCELACION);

ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT FK_DEPARTAMENTO_DIRECTOR FOREIGN KEY (IDDIRECTOR)
REFERENCES DIRECTOR (IDUSUARIO);

ALTER TABLE GRUPO
ADD CONSTRAINT FK_GRUPO_MATERIA FOREIGN KEY (IDMATERIA)
REFERENCES MATERIA (IDMATERIA);

ALTER TABLE PREINSCRIPCION
ADD CONSTRAINT FK_PREINSCRIPCION_ESTUDIANTE FOREIGN KEY (IDESTUDIANTE)
REFERENCES ESTUDIANTE (IDUSUARIO);

ALTER TABLE PREINSCRIPCION
ADD CONSTRAINT FK_PREINSCRIPCION_MATERIA FOREIGN KEY (IDMATERIA)
REFERENCES MATERIA (IDMATERIA);

ALTER TABLE CANCELACION
ADD CONSTRAINT FK_CANCELACION_MATERIA FOREIGN KEY (IDMATERIA)
REFERENCES MATERIA (IDMATERIA);

ALTER TABLE CANCELACION
ADD CONSTRAINT FK_CANCELACION_NOTIFICACION FOREIGN KEY (IDNOTIFICACION)
REFERENCES NOTIFICACION (IDNOTIFICACION);

ALTER TABLE AREA
ADD CONSTRAINT FK_AREA_DEPARTAMENTO FOREIGN KEY (IDDEPARTAMENTO)
REFERENCES DEPARTAMENTO (IDDEPARTAMENTO);

ALTER TABLE AREA
ADD CONSTRAINT FK_AREA_COORDINADOR FOREIGN KEY (IDCOORDINADOR)
REFERENCES COORDINADOR (IDUSUARIO);

ALTER TABLE MATERIA
ADD CONSTRAINT FK_MATERIA_AREA FOREIGN KEY (IDAREA)
REFERENCES AREA (IDAREA);

ALTER TABLE MATERIA
ADD CONSTRAINT FK_MATERIA_CENTRODEESTUDIOS FOREIGN KEY (IDCENTRODEESTUDIOS)
REFERENCES CENTRODEESTUDIOS (IDCENTRODEESTUDIOS);

ALTER TABLE MATERIA
ADD CONSTRAINT FK_MATERIA_ESTUDIANTE FOREIGN KEY (IDESTUDIANTE)
REFERENCES ESTUDIANTE (IDUSUARIO);

ALTER TABLE CENTRODEESTUDIOS
ADD CONSTRAINT FK_CENTRODEESTUDIOS_DIRECTOR FOREIGN KEY (IDDIRECTOR)
REFERENCES DIRECTOR (IDUSUARIO);

ALTER TABLE CENTRODEESTUDIOS
ADD CONSTRAINT FK_CENTRODEESTUDIOS_PROGRAMA FOREIGN KEY (IDPROGRAMAACADEMICO)
REFERENCES PROGRAMAACADEMICO (IDPROGRAMA);

ALTER TABLE NOTA
ADD CONSTRAINT FK_NOTA_MATERIA FOREIGN KEY (IDMATERIA)
REFERENCES MATERIA (IDMATERIA);

ALTER TABLE NOTA
ADD CONSTRAINT FK_NOTA_ESTUDIANTE FOREIGN KEY (IDESTUDIANTE)
REFERENCES ESTUDIANTE (IDUSUARIO);