ALTER TABLE USUARIO
ADD CONSTRAINT PK_USUARIO PRIMARY KEY (IDUSUARIO);

ALTER TABLE MATERIASPORESTUDIANTE
ADD CONSTRAINT PK_ESTUDIANTEM PRIMARY KEY (IDESTUDIANTE, IDMATERIA);

ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (IDDEPARTAMENTO);

ALTER TABLE GRUPO
ADD CONSTRAINT PK_GRUPO PRIMARY KEY (IDGRUPO);

ALTER TABLE PREINSCRIPCION
ADD CONSTRAINT PK_PREINSCRIPCION PRIMARY KEY (IDPREINSCRIPCION);

ALTER TABLE CANCELACION
ADD CONSTRAINT PK_CANCELACION PRIMARY KEY (IDCANCELACION);

ALTER TABLE AREA
ADD CONSTRAINT PK_AREA PRIMARY KEY (IDAREA);

ALTER TABLE NOTIFICACION
ADD CONSTRAINT PK_NOTIFICACION PRIMARY KEY (IDNOTIFICACION);

ALTER TABLE CENTRODEESTUDIOS
ADD CONSTRAINT PK_CENTRODEESTUDIOS PRIMARY KEY (IDCENTRODEESTUDIOS);

ALTER TABLE NUCLEODEFORMACION
ADD CONSTRAINT PK_NUCLEODEFORMACION PRIMARY KEY (IDNUCLEODEFORMACION);

ALTER TABLE NOTA
ADD CONSTRAINT PK_NOTA PRIMARY KEY (IDNOTA);

ALTER TABLE PROGRAMASPORESTUDIANTE
ADD CONSTRAINT PK_PROGRAMASPORESTUDIANTE PRIMARY KEY (IDPROGRAMA, IDESTUDIANTE);


